version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y nginx curl
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - cp /home/ubuntu/aws-continuous-delivery/nginx.conf /etc/nginx/sites-enabled/
      - service nginx restart
      - curl localhost
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
